resources:
  cloud: gcp
  accelerators: L4:1
  memory: 32+
  disk_size: 256

file_mounts:
  ~/sky_workdir/.env: ./.env
  ~/.gitconfig: ~/.gitconfig

workdir: .

setup: |
  echo -e "\n\n============   SKYPILOT SETUP: Start setup script.   ============\n\n"

  # ========== Libraries ==========
  sudo apt-get update
  
  # Hotfix: https://www.debian-fr.org/t/erreur-openssh-server-apres-upgrade/68781
  sudo apt-get purge openssh-server -y
  sudo apt-get install openssh-server -y

  sudo apt-get upgrade -y

  # Install common utilities
  sudo apt-get install -y \
      curl \
      fzf \
      git \
      git-all \
      htop \
      nano \
      unzip \
      wget \
      zip

  # Install development tools and libraries
  sudo apt-get install -y \
      build-essential \
      libbz2-dev \
      libc6-dev \
      libffi-dev \
      libgdbm-dev \
      liblzma-dev \
      libncursesw5-dev \
      libreadline-dev \
      libsqlite3-dev \
      libssl-dev \
      zlib1g-dev
  
  echo -e "\n\n============   SKYPILOT SETUP: Installed apt-get libraries.   ============\n\n"


  # ========== Setup .bashrc ==========
  cat << 'EOF' >> ~/.bashrc

  # =================================================================

  # -------------- Aliases --------------
  alias fzfenv="printenv | fzf"
  alias fzfpip="pip freeze | fzf"
  alias cvenv="python -m venv .venv"
  alias avenv="source .venv/bin/activate"
  alias gl="git log --oneline --graph --decorate"

  if [ -f ~/.bash_aliases ]; then
      . ~/.bash_aliases
  fi

  # =================================================================

  EOF
  echo -e "\n\n============   SKYPILOT SETUP: Initialized bashrc.   ============\n\n"
  
  
  # ========== Reload .bashrc ==========
  source ~/.bashrc
  echo -e "\n\n============   SKYPILOT SETUP: Reloaded bashrc.   ============\n\n"


  # ========== Set up Python ==========
  # Install Pyenv
  curl https://pyenv.run | bash

  # Add pyenv path to bashrc
  cat << 'EOF' >> ~/.bashrc

  # ------------------- pyenv -------------------

  export PYENV_ROOT="$HOME/.pyenv"
  [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"

  # =================================================================

  EOF

  source ~/.bashrc
  echo -e "\n\n============   SKYPILOT SETUP: Installed pyenv.   ============\n\n"


  # ========== Repository-specific ==========
  pyenv install $(cat .python-version)
  pyenv local
  echo -e "\n\n============   SKYPILOT SETUP: Installed and activated Python $(cat .python-version)   ============\n\n"
  
  cvenv
  echo -e "\n\n============   SKYPILOT SETUP: Created venv.   ============\n\n"
  
  avenv
  pip install -e .
  pip install -e ".[dev,interpretability]"
  echo -e "\n\n============   SKYPILOT SETUP: Installed Python deps in venv.   ============\n\n"
